spring.application.name=quizkot
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quiz_system}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:21100000}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# // Source - https://stackoverflow.com/q/48567562
# // Posted by gstackoverflow, modified by community. See post 'Timeline' for change history
# // Retrieved 2026-04-17, License - CC BY-SA 3.0

spring.application.admin.enabled=false
